name: 'PowerBI CICD'
description: '...'
author: TDF TECH AUTHORITY We 🎔 TECH
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  environment:
    description: 'Who to greet'
    required: true
  files:
    description: 'Assets to format'
    required: true
  separator:
    description: 'The character used to seperate file names'
    required: true
  composite-path:
    description: 'Composire directory path'
    required: true
  DEV_WORKSPACE:
    description: 'Workspace to Publish the PBIX'
    required: true
  DEV_FOLDER:
    description: 'dd'
    required: false
    default: "./Reports"
  URL_PowerAutomate_EndPoint:
    required: false
    description: "Endpoint to send notifications"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Setup PbiTool
      run: |
        $root_path = (Get-Location).Path
        $tool_folder_name = "pbi-tools.1.0.0-rc.1"
        $pbitoolPath = Join-Path $root_path $tool_folder_name
        Write-Information "$pbitoolPath  pbitoolPath"
        Write-Information "";${{ github.action_path }}\"$tool_folder_name"
        $env:PATH = $env:PATH + ";${{ github.action_path }}\"$tool_folder_name
        echo $env:PATH
      shell: pwsh