name: 'PowerBI CICD'
description: '...'
author: TDF TECH AUTHORITY We 🎔 TECH
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  environment:
    description: 'Who to greet'
    required: true
  files:
    description: 'Assets to format'
    required: true
  separator:
    description: 'The character used to seperate file names'
    required: true
  composite-path:
    description: 'Composire directory path'
    required: true
  DEV_WORKSPACE:
    description: 'Workspace to Publish the PBIX'
    required: true
  DEV_FOLDER:
    description: 'dd'
    required: false
    default: "./Reports"
  URL_PowerAutomate_EndPoint:
    required: false
    description: "Endpoint to send notifications"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Setup PbiTool
      run: |
        $root_path = (Get-Location).Path
        $tool_folder_name = "pbi-tools.1.0.0-rc.1"
        $pbitoolPath = Join-Path $root_path $tool_folder_name
        #$env:PATH = $env:PATH + $pbitoolPath
        #echo $env:PATH
        $executable = ${{ github.action_path }}/pbi-tools.1.0.0-rc.1/pbi-tools.exe
        #$executable pbi-tools info
        #$env:PATH = $env:PATH + $executable
        $executable pbi-tools info

        #$p = Start-Process -FilePath ${{ github.action_path }}/pbi-tools.1.0.0-rc.1/pbi-tools.exe -Wait -NoNewWindow -PassThru -ArgumentList pbi-tools info
        #if ($p.ExitCode -ne 0) {
        #  Write-Error "Faild"
        #}
      shell: pwsh